### ISSUE TITLE
Dreamer-v3 exp yaml file for vector gymnasium Env and evaluation from checkpoint?

### ISSUE THREAD

**Issue by hanshuo-shuo** [Eclectic-Sheep/sheeprl#122]
Hi, Thanks for this great library with all the sota model-based method,

I'm trying to use dreamer-v3 on my customed environment with only the vector observation. I find it hard to define the experiment file with only mlp-encoder. 

Do you have an example yaml file on dreamer-v3 with only vector observation? 

Right now my yaml file looks like 
```
defaults:
  - override /algo: dreamer_v3
  - override /env: gym
  - _self_

wrapper:
  _target_: gymnasium.make
  id: ${env.id}
  render_mode: None
  from_vectors: True
  max_episode_steps : 300

# Experiment
total_steps: 100000
per_rank_batch_size: 16
per_rank_sequence_length: 64
# Checkpoint
checkpoint:
  every: 100000

# Buffer
buffer:
  size: 1000000
  checkpoint: False

# Distribution
distribution:
  type: "auto"



mlp_keys:
  encoder:
    - state

# Algorithm
algo:
  learning_starts: 5000
  train_every: 50
  mlp_layers: 2
  world_model:
    recurrent_model:
      recurrent_state_size: 256
    transition_model:
      hidden_size: 256
    representation_model:
      hidden_size: 256
```

Although this can run, but I'm not sure this is the correct way to do so.

Thank you
