### ISSUE TITLE
[Error] The trainning and testing videos for MuJoCo Gymnasium always  have durations= 0s

### ISSUE THREAD

**Issue by LYK-love** [Eclectic-Sheep/sheeprl#191]
My env:
* I've installed all the dependencies via pip. I've set `MUJOCO_GL=egl` and installed `egl`. 
* My OS is Ubuntu22.04 x86_64.
* My python version is `3.9`.
* My cuda version is 12.3 (from `nvidia-smi`).
* My sheeprl version is `0.5.2`. I've run `git pull` before my trying.

I train my agent in  in the walker walk environment via:
```sh
python sheeprl.py exp=dreamer_v3 env=mujoco env.id=Walker2d-v4 algo.cnn_keys.encoder=[rgb]
```
This will start training the model and keep printing some logs to the CLI. However, at any given moment, the duration of the video files in dir `logs/runs/dreamer_v3/Walker2d-v4/2024-01-18_21-15-29_dreamer_v3_Walker2d-v4_42/version_0/train_videos` is always 0s. When I evaluate my checkpoint with command:
```sh
python sheeprl_eval.py checkpoint_path=/path/to/checkpoint.ckpt fabric.accelerator=gpu env.capture_video=True
```
The generated test videos under `logs/runs/dreamer_v3/Walker2d-v4/2024-01-18_21-15-29_dreamer_v3_Walker2d-v4_42/version_0/evaluation/version_0/train_videos` also have duration=0s.

This only happens to MuJoCo Gymnasium env `Walker2d-v4`. I believe it is unrelavant to dreamer algorithm. When I run:
```sh
python sheeprl.py exp=dreamer_v1 env=mujoco env.id=Walker2d-v4 algo.cnn_keys.encoder=[rgb]
```
or
```sh
python sheeprl.py exp=dreamer_v2 env=mujoco env.id=Walker2d-v4 algo.cnn_keys.encoder=[rgb]
```
The problem holds. 

But if I switch to other envs, the video duration seems to be normal. For instance, the video duration = 33s  with algorithm=dreamer_v3 and  env=`walker_walk`:
```sh
python sheeprl.py exp=dreamer_v3 env=dmc env.id=walker_walk algo.cnn_keys.encoder=[rgb]
```

The video duration = 33s  with algorithm=dreamer_v1 and  env=`walker_walk`:
```sh
python sheeprl.py exp=dreamer_v1 env=dmc env.id=walker_walk algo.cnn_keys.encoder=[rgb]
```

The video duration = 10swith algorithm=ppo and  env=`CartPole-v1`
```sh
python sheeprl.py fabric.accelerator=cpu fabric.strategy=ddp fabric.devices=2 exp=ppo env=gym env.id=CartPole-v1
```

The generated training and testing videos always have duration = 10s.

**Comment by LYK-love** [comment]
Hi, I tried your command and got a bunch of videos with duration > 20s. It seems fine. The training  just started 30s.

However, I ran the problematic command, which I reported in Github, for 10+ hours. I still got the same result (videos with duration=0). Can you reproduce my problem?

**Comment by michele-milesi** [comment]
Yeah, I will try to reproduce your error.
Have any configuration files been modified? This way I can reproduce the experiment exactly with the same configuration.
If any configuration file has been modified, can you please share the `config.yaml` file in the logging directory?

In the meantime, can you share the loss and reward charts?

**Comment by LYK-love** [comment]
No I didn't modify any config. The content of `sheeprl/configs/config.yaml` is:
```yaml
# @package _global_

# Specify here the default training configuration
defaults:
  - _self_
  - algo: default.yaml
  - buffer: default.yaml
  - checkpoint: default.yaml
  - distribution: default.yaml
  - env: default.yaml
  - fabric: default.yaml
  - metric: default.yaml
  - model_manager: default.yaml
  - hydra: default.yaml
  - exp: ???

num_threads: 1

# Set it to True to run a single optimization step
dry_run: False

# Reproducibility
seed: 42
torch_deterministic: False

# Output folders
exp_name: ${algo.name}_${env.id}
run_name: ${now:%Y-%m-%d_%H-%M-%S}_${exp_name}_${seed}
root_dir: ${algo.name}/${env.id}
```
