### ISSUE TITLE
fabric precision: `32` bit using far less memory than `bf16`

### ISSUE THREAD

**Issue by geranim0** [Eclectic-Sheep/sheeprl#240]
Hi, was playing with fabric precision and noticed that  `bf16` uses quite a bit more memory than `32` (23.83Gi vs 13.37Gi).  It also trains a little bit slower (1.77 Hz vs 1.91 Hz)
Wondering if it is expected behavior, or something's wrong somewhere?

Config: 
```yaml
defaults:
  - dreamer_v3
  - override /algo: dreamer_v3_XL
  - override /env: atari
  - _self_

# Experiment
seed: 5

# Environment
env:
  num_envs: 6
  max_episode_steps: 27000
  id: MsPacmanNoFrameskip-v4
  input_buffer: 12
  use_input_buf_as_obs: True

# Checkpoint
checkpoint:
  every: 2000

# Buffer
buffer:
  size: 100000
  checkpoint: True

# Algorithm
algo:
  learning_starts: 1024
  total_steps: 1200000
  train_every: 12
  per_rank_batch_size: 8
  per_rank_sequence_length: 98
  mlp_keys:
    encoder: [actions_0, actions_1, actions_2, actions_3, actions_4, actions_5, actions_6, actions_7, actions_8, actions_9, actions_10, actions_11]

fabric:
  precision: bf16

```

Memory using `precision: 32`, Training at 1.91 Hz.
![image](https://github.com/Eclectic-Sheep/sheeprl/assets/15318348/d298b13a-24fd-413a-b512-aca479e2142b)

Memory using `precision: bf16`, Training at 1.77 Hz.
![image](https://github.com/Eclectic-Sheep/sheeprl/assets/15318348/1442f61f-bb3a-4a9f-915e-b24cb5cd1471)
